# Workflow name and description
name: fourlands CI/CD
# Defines the events that trigger the workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
      - master
# Defines the jobs to be executeds
jobs:

  previous-test:
    runs-on: ubuntu-latest  # Defines the type of virtual machine that will run the job
    steps: 
      # Cancel previous executions of workflows still in progress for the same branch
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          acces_token: ${{ github.token }}
      # Checks out the code in the action's virtual machine
      - uses: actions/checkout@v2
      # Configure Java 17 for use in the workflow
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      # Grant execute permissions for the gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      # Run Checkstyle to ensure that the code complies with style standard
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest
      # Compile the project using Gradle

  build-general:    
    runs-on: ubuntu-latest  # Defines the type of virtual machine that will run the job    
    needs: previous-test
    steps:
      # Grant execute permissions for the gradlew script
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build --info
      # Configure Docker Buildx for building Docker images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Log in to DockerHub to allow image uploads
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.FOURLANDS_DOCKER_USER }}
          password: ${{ secrets.FOURLANDS_DOCKER_PASS }}
  build-for-master:  
    runs-on: ubuntu-latest  # Defines the type of virtual machine that will run the job    
    needs: build-general
    if: startsWith(github.ref, 'refs/heads/master')
    steps:
      # Build and upload a Docker image to the master branch
      - name: Build and push (master)        
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fourlandsdev/fourlandsprod:latest
  build-for-develop:
    runs-on: ubuntu-latest  # Defines the type of virtual machine that will run the job    
    needs: build-general
    if: startsWith(github.ref, 'refs/heads/develop')
    steps:
      # Build and upload a Docker image to the master branch
      - name: Build and push (develop)        
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: fourlandsdev/fourlandsdev:dev